[package]
name = "treeline"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "a library for visualizing tree structured data"
documentation = "https://softprops.github.io/treeline"
homepage = "https://github.com/softprops/treeline"
repository = "https://github.com/softprops/treeline"
keywords = ["tree"]
license = "MIT"
